exports.seed = async function(knex) {
  await knex('interests').del();

  await knex('interests').insert([
  { category: "Sport", name: "Basketball" },
  { category: "Sport", name: "Padel" },
  { category: "Sport", name: "Running Club" },
  { category: "Sport", name: "Gym" },
  { category: "Sport", name: "Functional Training" },
  { category: "Sport", name: "Cycling" },
  { category: "Sport", name: "Swimming" },
  { category: "Sport", name: "Tennis" },
  { category: "Sport", name: "Martial Arts" },
  { category: "Sport", name: "Street Workout" },

  { category: "Drink", name: "Specialty Coffee" },
  { category: "Drink", name: "Espresso Culture" },
  { category: "Drink", name: "Tea Rituals" },
  { category: "Drink", name: "Matcha" },
  { category: "Drink", name: "Cold Brew" },
  { category: "Drink", name: "Wine Tasting" },
  { category: "Drink", name: "Craft Beer" },
  { category: "Drink", name: "Mocktails" },
  { category: "Drink", name: "Coffee Shop Hopping" },
  { category: "Drink", name: "Bubble Tea" },

  { category: "Food", name: "Brunch" },
  { category: "Food", name: "Street Food" },
  { category: "Food", name: "Healthy Cooking" },
  { category: "Food", name: "BBQ" },
  { category: "Food", name: "Sushi" },
  { category: "Food", name: "Vegetarian Food" },
  { category: "Food", name: "Food Markets" },
  { category: "Food", name: "Late Dinner" },
  { category: "Food", name: "Dessert Places" },
  { category: "Food", name: "Home Cooking" },

  { category: "Tech", name: "Programming" },
  { category: "Tech", name: "AI Tools" },
  { category: "Tech", name: "Startups" },
  { category: "Tech", name: "Product Building" },
  { category: "Tech", name: "Cybersecurity" },
  { category: "Tech", name: "Gadgets" },
  { category: "Tech", name: "Web Development" },
  { category: "Tech", name: "Automation" },
  { category: "Tech", name: "Indie Hacking" },
  { category: "Tech", name: "Tech Podcasts" },

  { category: "Lifestyle", name: "Digital Detox" },
  { category: "Lifestyle", name: "Minimalism" },
  { category: "Lifestyle", name: "Slow Living" },
  { category: "Lifestyle", name: "Morning Routine" },
  { category: "Lifestyle", name: "Night Walks" },
  { category: "Lifestyle", name: "Work Cafes" },
  { category: "Lifestyle", name: "Weekend Escapes" },
  { category: "Lifestyle", name: "No-Phone Time" },
  { category: "Lifestyle", name: "Personal Growth" },
  { category: "Lifestyle", name: "Cozy Spaces" },

  { category: "Social", name: "Hookah" },
  { category: "Social", name: "Board Games" },
  { category: "Social", name: "Meetups" },
  { category: "Social", name: "Deep Conversations" },
  { category: "Social", name: "Coffee Dates" },
  { category: "Social", name: "Networking" },
  { category: "Social", name: "Group Trips" },
  { category: "Social", name: "Cinema Nights" },
  { category: "Social", name: "Game Nights" },
  { category: "Social", name: "Small Gatherings" },

  { category: "Culture", name: "Cinema" },
  { category: "Culture", name: "Documentaries" },
  { category: "Culture", name: "Podcasts" },
  { category: "Culture", name: "Books" },
  { category: "Culture", name: "Modern History" },
  { category: "Culture", name: "Psychology" },
  { category: "Culture", name: "Stand-up Comedy" },
  { category: "Culture", name: "Live Music" },
  { category: "Culture", name: "Art Spaces" },
  { category: "Culture", name: "Photography" },

  { category: "Travel", name: "Road Trips" },
  { category: "Travel", name: "Nature Trips" },
  { category: "Travel", name: "Sea View Spots" },
  { category: "Travel", name: "Mountains" },
  { category: "Travel", name: "City Exploring" },
  { category: "Travel", name: "Hidden Places" },
  { category: "Travel", name: "Weekend Flights" },
  { category: "Travel", name: "Camping" },
  { category: "Travel", name: "Sunset Locations" },
  { category: "Travel", name: "Local Adventures" },

  { category: "Wellness", name: "Meditation" },
  { category: "Wellness", name: "Breathwork" },
  { category: "Wellness", name: "Sleep Optimization" },
  { category: "Wellness", name: "Healthy Habits" },
  { category: "Wellness", name: "Cold Showers" },
  { category: "Wellness", name: "Stretching" },
  { category: "Wellness", name: "Mental Clarity" },
  { category: "Wellness", name: "Journaling" },
  { category: "Wellness", name: "Mindfulness" },
  { category: "Wellness", name: "Recovery Days" },

  { category: "Modern Trends", name: "Reading Retreats" },
  { category: "Modern Trends", name: "Creative Workshops" },
  { category: "Modern Trends", name: "Ceramics" },
  { category: "Modern Trends", name: "Analog Hobbies" },
  { category: "Modern Trends", name: "Vinyl Culture" },
  { category: "Modern Trends", name: "Letterboxd" },
  { category: "Modern Trends", name: "Micro Communities" },
  { category: "Modern Trends", name: "Third Places" },
  { category: "Modern Trends", name: "Offline Sundays" },
  { category: "Modern Trends", name: "Whimsy Lifestyle" }
  ])
};
